### ISSUE TITLE
Sync issue locks me out of web apps

### ISSUE THREAD

**Issue by pyrosmiley** [cbrooker/MMM-Todoist#18]
I've made the fun discovery that when this module is running, other todoist clients that use the sync API (the web app, native OSX app, etc) can't load/are stuck in Offline mode. I have not yet taken a deep look into the sync API methods so I don't know how, but it's been driving me nuts that I can't use Todoist on a desktop for a couple of weeks, and I only just now figured out that this is the culprit. 

Now that I know, I can at least quit the MagicMirror to use todoist on the web but that's pretty hacky. When I have a chance I'll read through their documentation to see if I can figure out what the deal is -- it used to work just fine so I'll bet that when they updated their API (which caused this module to blank before!), something changed that it doesn't like anymore.

**Comment by pyrosmiley** [comment]
PS sorry for throwing issue after issue at this poor guy, I really like the module and absolutely could not make anything half as nice

**Comment by SamPUG** [comment]
I have also had this issue. I believe the problem is that at some point the config setting which does the refresh interval was changed. In the documentation it says that the interval is in seconds whereas it is actually in milliseconds. If you use the example config file then the module is trying to update far too often. I suspect that todoist has some kind of ip protection which puts a timeout on your ip for putting in to many requests.

**Comment by pyrosmiley** [comment]
@SamPUG that makes a lot of sense! I'll mess with things ASAP and report back.

**Comment by pyrosmiley** [comment]
@SamPUG Yep, things seem fine now. Wow, months of frustrations and it was that one stupid thing... thanks so much for dropping in! I'll put in a pull request.
