### ISSUE TITLE
Label filter does not work

### ISSUE THREAD

**Issue by lost-cassette** [cbrooker/MMM-Todoist#68]
Hey there! :)

I'm trying to create a list what showing every item containing the label "Monitor". Unfortunately it does not show anything besides the header.

I tried single & double quotes, with or without a prefix "@" or "%40", with the capital or only lowercase but everything does not seem to help. I'm I the only one with this problem? And if so, can some one maybe tell me what I'm doing wrong? :)

```module: 'MMM-Todoist',
position: 'bottom_left',
header: 'Monitor',
	 config: { 
		 accessToken: 'mytoken',
		 maximumEntries: 60,
		 updateInterval: 60*1000,
		 fade: false,
		 labels: [ "Monitor" ], 
		 displayTasksWithoutDue: true,
		 displayTasksWithinDays: -1,
		 maxTitleLength: 50,
	 }

**Comment by vanessa** [comment]
Same thing happening to me!

**Comment by cbrooker** [comment]
Labels are a feature only available in Todoist Premium. Unfortunately, I no longer have Premium and am unable to test this feature.

Is someone able to debug and fix?

**Comment by cbrooker** [comment]
Hi All,

I managed to find a code for 3 months of Premium so that I could test this out. Everything in the latest version is working correctly.

Things to keep in mind that if you specify "Projects" and "Labels" everything that matches either will be included. If you just want to display Todos from a label but not a whole project than leave project as an empty array [].

**Comment by lost-cassette** [comment]
Hey @cbrooker (& @vanessa ),

I just re-installed the module for a third time and now the label filter is working! I don't know what's different this time but I suspect some human error (me ;)) with the former attempt with re-installing to fix the problem.

Thank you for your effort and checking! :)
